In [1]:
import pandas as pd

In [2]:
jan = "JC-202001-citibike-tripdata.csv"
feb = "JC-202002-citibike-tripdata.csv"
mar = "JC-202003-citibike-tripdata.csv"
apr = "JC-202004-citibike-tripdata.csv"
may = "JC-202005-citibike-tripdata.csv"
jun = "JC-202006-citibike-tripdata.csv"

In [3]:
Jan = pd.read_csv(jan)

In [4]:
Jan["starttime"][0]

'2020-01-01 00:04:50.1920'

In [5]:
Jan[['startdate', 'starttime']] = Jan.starttime.str.split(expand=True)

In [6]:
Jan[['stopdate', 'stoptime']] = Jan.stoptime.str.split(expand=True)

In [7]:
Jan = Jan[['tripduration','startdate','starttime','stopdate','stoptime','start station id','start station name','start station latitude','start station longitude','end station id','end station name','end station latitude','end station longitude','bikeid','usertype','birth year','gender']]

In [8]:
len(Jan)

26020

In [9]:
Feb = pd.read_csv(feb)

In [10]:
Feb[['startdate', 'starttime']] = Feb.starttime.str.split(expand=True)

In [11]:
Feb[['stopdate', 'stoptime']] = Feb.stoptime.str.split(expand=True)

In [12]:
Feb = Feb[['tripduration','startdate','starttime','stopdate','stoptime','start station id','start station name','start station latitude','start station longitude','end station id','end station name','end station latitude','end station longitude','bikeid','usertype','birth year','gender']]

In [13]:
Feb.head()

,tripduration,startdate,starttime,stopdate,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,841,2020-02-01,00:02:13.7650,2020-02-01,00:16:15.4720,3199,Newport Pkwy,40.728745,-74.032108,3213,Van Vorst Park,40.718489,-74.047727,42217,Subscriber,1980,1
1,206,2020-02-01,00:16:11.3850,2020-02-01,00:19:37.4460,3273,Manila & 1st,40.721651,-74.042884,3639,Harborside,40.719252,-74.034234,42160,Subscriber,1990,1
2,859,2020-02-01,00:23:22.1090,2020-02-01,00:37:41.5060,3185,City Hall,40.717733,-74.043845,3268,Lafayette Park,40.713464,-74.062859,42204,Customer,1991,1
3,693,2020-02-01,00:25:14.5170,2020-02-01,00:36:48.0280,3185,City Hall,40.717733,-74.043845,3277,Communipaw & Berry Lane,40.714358,-74.066611,42165,Subscriber,1987,1
4,1473,2020-02-01,00:32:30.5050,2020-02-01,00:57:04.3740,3192,Liberty Light Rail,40.711242,-74.055701,3639,Harborside,40.719252,-74.034234,26156,Customer,1969,0

In [14]:
Mar = pd.read_csv(mar)

In [15]:
Mar[['startdate', 'starttime']] = Mar.starttime.str.split(expand=True)

In [16]:
Mar[['stopdate', 'stoptime']] = Mar.stoptime.str.split(expand=True)

In [17]:
Mar = Mar[['tripduration','startdate','starttime','stopdate','stoptime','start station id','start station name','start station latitude','start station longitude','end station id','end station name','end station latitude','end station longitude','bikeid','usertype','birth year','gender']]

In [18]:
Mar.head()

,tripduration,startdate,starttime,stopdate,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,389,2020-03-01,00:14:07.0000,2020-03-01,00:20:36.0880,3202,Newport PATH,40.727224,-74.033759,3203,Hamilton Park,40.727596,-74.044247,42381,Subscriber,1992,1
1,242,2020-03-01,00:48:06.4390,2020-03-01,00:52:08.9870,3185,City Hall,40.717733,-74.043845,3205,JC Medical Center,40.716540,-74.049638,42155,Subscriber,1991,1
2,124,2020-03-01,01:08:46.4880,2020-03-01,01:10:51.2780,3272,Jersey & 3rd,40.723332,-74.045953,3278,Monmouth and 6th,40.725685,-74.048790,42376,Subscriber,1987,0
3,104,2020-03-01,01:22:35.4790,2020-03-01,01:24:20.2470,3202,Newport PATH,40.727224,-74.033759,3638,Washington St,40.724294,-74.035483,42350,Subscriber,1993,1
4,228,2020-03-01,01:39:20.2680,2020-03-01,01:43:09.1380,3194,McGinley Square,40.725340,-74.067622,3280,Astor Place,40.719282,-74.071262,42235,Subscriber,1988,1

In [19]:
Apr = pd.read_csv(apr)

In [20]:
Apr[['startdate', 'starttime']] = Apr.starttime.str.split(expand=True)

In [21]:
Apr[['stopdate', 'stoptime']] = Apr.stoptime.str.split(expand=True)

In [25]:
Apr = Apr[['tripduration','startdate','starttime','stopdate','stoptime','start station id','start station name','start station latitude','start station longitude','end station id','end station name','end station latitude','end station longitude','bikeid','usertype','birth year','gender']]

In [26]:
Apr.head()

,tripduration,startdate,starttime,stopdate,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1437,2020-04-01,01:06:20.6300,2020-04-01,01:30:17.9680,3678,Fairmount Ave,40.725726,-74.071959,3678,Fairmount Ave,40.725726,-74.071959,42314,Customer,2002,2
1,264,2020-04-01,05:02:42.0570,2020-04-01,05:07:06.1260,3207,Oakland Ave,40.737604,-74.052478,3195,Sip Ave,40.730897,-74.063913,42146,Subscriber,1963,2
2,254,2020-04-01,06:20:28.1190,2020-04-01,06:24:42.1380,3678,Fairmount Ave,40.725726,-74.071959,3195,Sip Ave,40.730897,-74.063913,42255,Subscriber,1981,1
3,429,2020-04-01,06:33:30.5170,2020-04-01,06:40:40.1990,3195,Sip Ave,40.730897,-74.063913,3679,Bergen Ave,40.722104,-74.071455,42529,Subscriber,1964,1
4,805,2020-04-01,06:38:32.9220,2020-04-01,06:51:58.2050,3193,Lincoln Park,40.724605,-74.078406,3195,Sip Ave,40.730897,-74.063913,42362,Subscriber,1965,1

In [27]:
May = pd.read_csv(may)

In [29]:
May[['startdate', 'starttime']] = May.starttime.str.split(expand=True)

In [30]:
May[['stopdate', 'stoptime']] = May.stoptime.str.split(expand=True)

In [31]:
May = May[['tripduration','startdate','starttime','stopdate','stoptime','start station id','start station name','start station latitude','start station longitude','end station id','end station name','end station latitude','end station longitude','bikeid','usertype','birth year','gender']]

In [32]:
May.head()

,tripduration,startdate,starttime,stopdate,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,349,2020-05-01,00:09:45.5860,2020-05-01,00:15:35.2930,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,42581,Customer,1969,0
1,138,2020-05-01,01:11:22.5280,2020-05-01,01:13:41.2460,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,3639,Harborside,40.719252,-74.034234,42105,Subscriber,1949,1
2,229,2020-05-01,05:31:29.5350,2020-05-01,05:35:19.2400,3483,Montgomery St,40.719420,-74.050990,3186,Grove St PATH,40.719586,-74.043117,42320,Customer,1984,1
3,261,2020-05-01,05:51:39.3960,2020-05-01,05:56:00.9370,3278,Monmouth and 6th,40.725685,-74.048790,3186,Grove St PATH,40.719586,-74.043117,42170,Subscriber,1974,2
4,168,2020-05-01,06:06:31.9510,2020-05-01,06:09:20.1410,3194,McGinley Square,40.725340,-74.067622,3195,Sip Ave,40.730897,-74.063913,42352,Subscriber,1966,1

In [22]:
Jun = pd.read_csv(jun)

In [33]:
Jun[['startdate', 'starttime']] = Jun.starttime.str.split(expand=True)

In [35]:
Jun[['stopdate', 'stoptime']] = Jun.stoptime.str.split(expand=True)

In [36]:
Jun = Jun[['tripduration','startdate','starttime','stopdate','stoptime','start station id','start station name','start station latitude','start station longitude','end station id','end station name','end station latitude','end station longitude','bikeid','usertype','birth year','gender']]

In [37]:
Half2020 = Jan.append([Feb, Mar, Apr, May, Jun], ignore_index=True)

In [38]:
Half2020

,tripduration,startdate,starttime,stopdate,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,226,2020-01-01,00:04:50.1920,2020-01-01,00:08:37.0370,3186,Grove St PATH,40.719586,-74.043117,3211,Newark Ave,40.721525,-74.046305,29444,Subscriber,1984,2
1,377,2020-01-01,00:16:01.6700,2020-01-01,00:22:19.0800,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,26305,Subscriber,1989,2
2,288,2020-01-01,00:17:33.8770,2020-01-01,00:22:22.4420,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,29268,Customer,1989,1
3,435,2020-01-01,00:32:05.9020,2020-01-01,00:39:21.0660,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,29278,Customer,1969,0
4,231,2020-01-01,00:46:19.6780,2020-01-01,00:50:11.3440,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,29276,Subscriber,1983,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137962,2828,2020-06-30,23:53:19.7380,2020-07-01,00:40:28.5760,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,18351,Customer,1969,0
137963,2729,2020-06-30,23:54:44.0100,2020-07-01,00:40:13.6470,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,44401,Customer,1969,0
137964,2788,2020-06-30,23:54:52.1920,2020-07-01,00:41:20.6500,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,42334,Customer,1969,0
137965,2702,2020-06-30,23:56:14.6650,2020-07-01,00:41:16.7820,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,42463,Customer,1969,0
137966,2649,2020-06-30,23:57:46.1490,2020-07-01,00:41:55.5060,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,42468,Customer,1998,2

In [41]:
Half2020.to_csv("Jan-Jun-Citibike-tripdata-2020.csv", index=False)